
name: "Pull Request"
on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install packages
        run: yarn

      - name: Check linting
        run: yarn lint:check

      - name: Check formatting
        run: yarn format:check